CandyShop/Controllers/CandyController.cs
using CandyShop.Models;
using CandyShop.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CandyShop.Controllers
{
    public class CandyController : Controller
    {
        private readonly ICandyRepository _candyRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly AppDbContext _appDbContext;
        private readonly IWebHostEnvironment WebHostEnvironment;

        public CandyController(ICandyRepository candyRepository, ICategoryRepository categoryRepository, AppDbContext appDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _candyRepository = candyRepository;
            _categoryRepository = categoryRepository;
            _appDbContext = appDbContext;
            WebHostEnvironment = webHostEnvironment;
        }

        public ViewResult List(PyjamaViewModel obj, string category)
        {
            IEnumerable<Candy> candies;
            string currentCategory;


            if (string.IsNullOrEmpty(category))
            {
                candies = _candyRepository.GetAllCandy.OrderBy(c => c.CandyId);
                currentCategory = "All Candy";
            } 
            else
            {
                candies = _candyRepository.GetAllCandy.Where(c => c.Category.CategoryName == category);
                currentCategory = _categoryRepository.GetAllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new CandyListViewModel
            {
                Candies = candies,
                CurrentCategory = currentCategory
            });
        }
        public ViewResult SerachPhraseResult(PyjamaViewModel obj, string category, string SearchResult)
        {
            IEnumerable<Candy> candies;
            string currentCategory;


            if (string.IsNullOrEmpty(category))
            {
                candies = _candyRepository.GetAllCandy.OrderBy(c => c.CandyId);
                currentCategory = "All Candy";
            }
            else
            {
                candies = _candyRepository.GetAllCandy.Where(c => c.Name.Contains(SearchResult));
                currentCategory = _categoryRepository.GetAllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new CandyListViewModel
            {
                Candies = candies,
                CurrentCategory = currentCategory
            });
        }


            public ViewResult Index(PyjamaViewModel obj, string category)
        {
            IEnumerable<Candy> candies;
            string currentCategory;


            if (string.IsNullOrEmpty(category))
            {
                candies = _candyRepository.GetAllCandy.OrderBy(c => c.CandyId);
                currentCategory = "All Candy";
            }
            else
            {
                candies = _candyRepository.GetAllCandy.Where(c => c.Category.CategoryName == category);
                currentCategory = _categoryRepository.GetAllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new CandyListViewModel
            {
                Candies = candies,
                CurrentCategory = currentCategory
            });
        }



        public IActionResult Details(int id)
        {
            var candy = _candyRepository.GetCandyById(id);
            if (candy == null)
            {
                return NotFound();
            }
            return View(candy);
        }

        public IActionResult Create()
        {


            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PyjamaViewModel obj)
        {
            string stringFilename = FileUpload(obj);
            string stringFilename2 = FileUpload2(obj);
            var pyjama = new Candy
            {
                Name = obj.Name,
                Price = obj.Price,
                ImageThumbnailUrl = stringFilename,
                Description = obj.Description,
                ImageUrl = stringFilename2,
                CategoryId = obj.CategoryId,
                Category = obj.Category,
                IsInStock =obj.IsInStock,
                IsOnSale = obj.IsOnSale
            };

            _appDbContext.Candies.Add(pyjama);
            _appDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        private string FileUpload(PyjamaViewModel obj)
        {
            string fileName = null;
            if (obj.ImageThumbnailUrl!= null)
            {
                string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "Images/thumbnails");
                fileName = Guid.NewGuid().ToString() + "-" + obj.ImageThumbnailUrl.FileName;
                string filepath = Path.Combine(uploadDir, fileName);
                using (var filestream = new FileStream(filepath, FileMode.Create))
                {
                    obj.ImageThumbnailUrl.CopyTo(filestream);
                }
            }
            return "\\Images\\thumbnails\\"+fileName;
        }
        private string FileUpload2(PyjamaViewModel obj)
        {
            string fileName = null;
            if (obj.ImageUrl != null)
            {
                string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "Images/");
                fileName = Guid.NewGuid().ToString() + "-" + obj.ImageUrl.FileName;
                string filepath = Path.Combine(uploadDir, fileName);
                using (var filestream = new FileStream(filepath, FileMode.Create))
                {
                    obj.ImageUrl.CopyTo(filestream);
                }
            }
            return "\\Images\\" + fileName;
        }




        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pyjama = await _appDbContext.Candies
                .FirstOrDefaultAsync(m => m.CandyId == id);
            if (pyjama == null)
            {
                return NotFound();
            }

            return View(pyjama);
        }

        // POST: Pyjamas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pyjama = await _appDbContext.Candies.FindAsync(id);
            _appDbContext.Candies.Remove(pyjama);
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PyjamaExists(int id)
        {
            return _appDbContext.Candies.Any(e => e.CandyId == id);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pyjama = await _appDbContext.Candies.FindAsync(id);
            if (pyjama == null)
            {
                return NotFound();
            }
            return View(pyjama);
        }

        // POST: Pyjamas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,ProfileImage")] Candy pyjama)
        {
            if (id != pyjama.CandyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _appDbContext.Update(pyjama);
                    await _appDbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PyjamaExists(pyjama.CandyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pyjama);
        }

    }
}

CandyShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CandyShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();  
        }

    }
}

CandyShop/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/kekela1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/kekelaerti2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/kekelaerti3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

CandyShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        @await Component.InvokeAsync("CategoryMenu")
                        <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" src="~/Images/kekelaLogo.jpg" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
        @RenderSection("Scripts",required: false)  
    </div>
</body>
</html>

CandyShop/Views/Shared/_candyCard.cshtml
@model Candy

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="image for candy shop" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3><a asp-controller="Candy" asp-action="Details" asp-route-id="@Model.CandyId">@Model.Name</a></h3>
            <p>@Model.Description</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-candyId="@Model.CandyId">Add to Cart</a>
            </p>
        </div>
    </div>
</div>

CandyShop/Views/Shared/_candyIndex.cshtml
@model Candy

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="image for candy shop" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3><a asp-controller="Candy" asp-action="Details" asp-route-id="@Model.CandyId">@Model.Name</a></h3>
            <p>@Model.Description</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="Candy" asp-action="Edit" asp-route-Id="@Model.CandyId">Edit</a>
                <a class="btn btn-primary" asp-controller="Candy" asp-action="Delete" asp-route-Id="@Model.CandyId">Delete</a>

            </p>
        </div>
    </div>
</div>