CandyShop/Models/Candy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CandyShop.Models
{
    public class Candy
    {
        public int CandyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        [Column(TypeName="decimal(18,2)")]
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public string ImageThumbnailUrl { get; set; }
        public bool IsOnSale { get; set; }
        public bool IsInStock { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

CandyShop/Controllers/CandyController.cs
using CandyShop.Models;
using CandyShop.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CandyShop.Controllers
{
    public class CandyController : Controller
    {
        private readonly ICandyRepository _candyRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly AppDbContext _appDbContext;
        private readonly IWebHostEnvironment WebHostEnvironment;

        public CandyController(ICandyRepository candyRepository, ICategoryRepository categoryRepository, AppDbContext appDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _candyRepository = candyRepository;
            _categoryRepository = categoryRepository;
            _appDbContext = appDbContext;
            WebHostEnvironment = webHostEnvironment;
        }

        public ViewResult List(PyjamaViewModel obj, string category)
        {
            IEnumerable<Candy> candies;
            string currentCategory;


            if (string.IsNullOrEmpty(category))
            {
                candies = _candyRepository.GetAllCandy.OrderBy(c => c.CandyId);
                currentCategory = "All Candy";
            } 
            else
            {
                candies = _candyRepository.GetAllCandy.Where(c => c.Category.CategoryName == category);
                currentCategory = _categoryRepository.GetAllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new CandyListViewModel
            {
                Candies = candies,
                CurrentCategory = currentCategory
            });
        }
        public ViewResult SerachPhraseResult(PyjamaViewModel obj, string category, string SearchResult)
        {
            IEnumerable<Candy> candies;
            string currentCategory;


            if (string.IsNullOrEmpty(category))
            {
                candies = _candyRepository.GetAllCandy.OrderBy(c => c.CandyId);
                currentCategory = "All Candy";
            }
            else
            {
                candies = _candyRepository.GetAllCandy.Where(c => c.Name.Contains(SearchResult));
                currentCategory = _categoryRepository.GetAllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new CandyListViewModel
            {
                Candies = candies,
                CurrentCategory = currentCategory
            });
        }


            public ViewResult Index(PyjamaViewModel obj, string category)
        {
            IEnumerable<Candy> candies;
            string currentCategory;


            if (string.IsNullOrEmpty(category))
            {
                candies = _candyRepository.GetAllCandy.OrderBy(c => c.CandyId);
                currentCategory = "All Candy";
            }
            else
            {
                candies = _candyRepository.GetAllCandy.Where(c => c.Category.CategoryName == category);
                currentCategory = _categoryRepository.GetAllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new CandyListViewModel
            {
                Candies = candies,
                CurrentCategory = currentCategory
            });
        }



        public IActionResult Details(int id)
        {
            var candy = _candyRepository.GetCandyById(id);
            if (candy == null)
            {
                return NotFound();
            }
            return View(candy);
        }

        public IActionResult Create()
        {


            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PyjamaViewModel obj)
        {
            string stringFilename = FileUpload(obj);
            string stringFilename2 = FileUpload2(obj);
            var pyjama = new Candy
            {
                Name = obj.Name,
                Price = obj.Price,
                ImageThumbnailUrl = stringFilename,
                Description = obj.Description,
                ImageUrl = stringFilename2,
                CategoryId = obj.CategoryId,
                Category = obj.Category,
                IsInStock =obj.IsInStock,
                IsOnSale = obj.IsOnSale
            };

            _appDbContext.Candies.Add(pyjama);
            _appDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        private string FileUpload(PyjamaViewModel obj)
        {
            string fileName = null;
            if (obj.ImageThumbnailUrl!= null)
            {
                string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "Images/thumbnails");
                fileName = Guid.NewGuid().ToString() + "-" + obj.ImageThumbnailUrl.FileName;
                string filepath = Path.Combine(uploadDir, fileName);
                using (var filestream = new FileStream(filepath, FileMode.Create))
                {
                    obj.ImageThumbnailUrl.CopyTo(filestream);
                }
            }
            return "\\Images\\thumbnails\\"+fileName;
        }
        private string FileUpload2(PyjamaViewModel obj)
        {
            string fileName = null;
            if (obj.ImageUrl != null)
            {
                string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "Images/");
                fileName = Guid.NewGuid().ToString() + "-" + obj.ImageUrl.FileName;
                string filepath = Path.Combine(uploadDir, fileName);
                using (var filestream = new FileStream(filepath, FileMode.Create))
                {
                    obj.ImageUrl.CopyTo(filestream);
                }
            }
            return "\\Images\\" + fileName;
        }




        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pyjama = await _appDbContext.Candies
                .FirstOrDefaultAsync(m => m.CandyId == id);
            if (pyjama == null)
            {
                return NotFound();
            }

            return View(pyjama);
        }

        // POST: Pyjamas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pyjama = await _appDbContext.Candies.FindAsync(id);
            _appDbContext.Candies.Remove(pyjama);
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PyjamaExists(int id)
        {
            return _appDbContext.Candies.Any(e => e.CandyId == id);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pyjama = await _appDbContext.Candies.FindAsync(id);
            if (pyjama == null)
            {
                return NotFound();
            }
            return View(pyjama);
        }

        // POST: Pyjamas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,ProfileImage")] Candy pyjama)
        {
            if (id != pyjama.CandyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _appDbContext.Update(pyjama);
                    await _appDbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PyjamaExists(pyjama.CandyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pyjama);
        }

    }
}

CandyShop/Controllers/ShoppingCartController.cs
using CandyShop.Models;
using CandyShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CandyShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ICandyRepository _candyRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(ICandyRepository candyRepository, ShoppingCart shoppingCart)
        {
            _candyRepository = candyRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            _shoppingCart.ShoppingCartItems = _shoppingCart.GetShoppingCartItems();

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int candyId)
        {
            var selectedCandy = _candyRepository.GetAllCandy.FirstOrDefault(c => c.CandyId == candyId);

            if(selectedCandy != null)
            {
                _shoppingCart.AddToCart(selectedCandy, 1);
            }

            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromShoppingCart(int candyId)
        {
            var selectedCandy = _candyRepository.GetAllCandy.FirstOrDefault(c => c.CandyId == candyId);

            if (selectedCandy != null)
            {
                _shoppingCart.RemoveFromCart(selectedCandy);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult ClearCarT()
        {
            _shoppingCart.ClearCart();
            return RedirectToAction("Index");
        }

    }
}

CandyShop/Views/Candy/Create.cshtml
@model CandyShop.Models.Candy

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Candy</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input type="file" asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageThumbnailUrl" class="control-label"></label>
                <input type="file" asp-for="ImageThumbnailUrl" class="form-control" />
                <span asp-validation-for="ImageThumbnailUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsOnSale" /> @Html.DisplayNameFor(model => model.IsOnSale)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsInStock" /> @Html.DisplayNameFor(model => model.IsInStock)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></input>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CandyShop/Views/Candy/Delete.cshtml
@model CandyShop.Models.Candy

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Candy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageThumbnailUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageThumbnailUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsOnSale)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsOnSale)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsInStock)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsInStock)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CandyId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CandyShop/Views/Candy/Details.cshtml
@model Candy

<h1>@Model.Name</h1>

<div class="thumbnail">
    <img alt="@Model.Name" src="@Model.ImageUrl" />
    <div class="caption-full">
        <h3 class="pull-right">@Model.Price</h3>
        <h3><a href="#">@Model.Name</a></h3>
        <p>@Model.Description</p>
    </div>
    <div class="addToCart">
        <p class="button">
            <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-candyId="@Model.CandyId">Add to Cart</a>
        </p>
    </div>

</div>

CandyShop/Views/Candy/Index.cshtml
@model CandyListViewModel

<div class="row">
    <a class="btn btn-primary" asp-controller="Candy" asp-action="Create">Create</a>
</div>
@foreach (var candy in Model.Candies)
{
    <partial name="_candyIndex" model="candy" />
    
}  

CandyShop/Views/Candy/List.cshtml
@model CandyListViewModel

 <h1>@Model.CurrentCategory</h1>
@foreach(var candy in Model.Candies)
{
    <partial name="_candyCard" model="candy" />

}  

CandyShop/Views/Candy/SearchPhraseResult.cshtml
@model CandyShop.Models.Candy

@{
    ViewData["Title"] = "SearchPhraseResult";
}

<h2>SearchPhraseResult</h2>

<h4>Candy</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SearchPhraseResult">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
                <button>submit</button>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}